### ISSUE TITLE
Build errors after enabling precompiled headers

### ISSUE THREAD

**Issue by AayuStark007** [TheCherno/Hazel#11]
After enabling precompiled headers from following through the video, when I ran the rebuild/build all command on my own fork of the project, I got a ton of errors and the build failed. 
The same thing happens when I try to build the latest clone of this project.

The detailed build log for Hazel can be found at: 
[hazel_build](https://gist.github.com/AayuStark007/dea01bcbfe141339b95e55b0ca374ed1)

I get the exact same errors when building my own fork of Hazel.

**Comment by nfwGytautas** [comment]
This is most likely due to you using the old version of spdlog. If I remember correctly spdlog defines MIN MAX macros which are also defined in Windows.h. One solution is to not include Windows.h in your pch another is to pull (go to vendor\spdlog; run git; write 'git pull') the new version of spdlog.

**Comment by AayuStark007** [comment]
@nfwGytautas Yes, that does it. Thank you! :smiley:
