### ISSUE TITLE
Unhandled  exception error

### ISSUE THREAD

**Issue by mjm2017** [TheCherno/Hazel#133]
You get an error at all these call functions. 
glCreateVertexArrays(1, &m_RendererID);

Unhandled exception at 0x0000000000000000 in Sandbox.exe: 0xC0000005: Access violation executing location 0x0000000000000000. occurred

m_RendererID is not initialized but used

**Comment by IshoAntar** [comment]
A stack-trace would be helpful.

**Comment by LovelySanta** [comment]
one solution could be to set `uint32_t m_RendererID = 0;` in the header file...

**Comment by ReDucTor** [comment]
The error shows it's the this pointer that is invalid not the value of the renderer id,  a stack trace is needed to see where a null instance exisrs

**Comment by IshoAntar** [comment]
@LovelySanta actually that's probably not the issue since i've tried removing it from the constructor's initializer list and it didn't make any difference? but it might be different for him.
anyway, a solution that he could try is to initialize it to 0 in the constructor/header file.

**Comment by mjm2017** [comment]
Even if you initialized with zero, it still doesn't work. You have to give an object to that variable. Or a real default value that the m_RendererID is representing.

**Comment by WhoseTheNerd** [comment]
Did you create opengl 4.5 context?

**Comment by LovelySanta** [comment]
> @LovelySanta actually that's probably not the issue since i've tried removing it from the constructor's initializer list and it didn't make any difference (it worked just fine)? but it might be different for him.
> anyway, as you suggested a solution that he could try is to initialize it to 0 in the constructor/header file and see if it works.

It's not an issue for me either, it just works for me, and I don't see why it shouldn't work.

@mjm2017 can you reproduce this with the (current) master branch of Hazel itself (not some code-along?)

Until this is confirmed to be an issue on this Hazel repo, I'll unmark it as a bug.

**Comment by mjm2017** [comment]
I have up-to-date git pull that causes the issue. So, I don't know how it works for you.

**Comment by IshoAntar** [comment]
OK, so i managed to reproduce the issue by not initializing GLAD (i commented out lines `19`, `20` in `OpenGLContext.cpp`).
so @mjm2017:
1. do you still have the `HZ_CORE_INFO` statements that print out the OpenGL info in that file (lines `22`-`25`)? i'm asking because i got the same exception as you did but from `glGetString`, since the execution didn't get to `glCreateVertexArrays` because of those statements.
2. Are you initializing GLAD `gladLoadGLLoader((GLADloadproc)glfwGetProcAddress)` before attempting to call any GL function?

**Comment by mjm2017** [comment]
Dear IshoAntar, 
I did nothing .. I just wanted to try out the code after a long time a way from the code of the Hazel engine. I tried to re-sync my knowledge.. thats it.
So I tried nothing.. just pulling the code and compiling it. and I get the errors. 
thanks.

**Comment by IshoAntar** [comment]
Now that's weird!
I will try to re-clone the repo and building it, and see if i get any problems

**Comment by mjm2017** [comment]
[18:05:39] HAZEL: Initialized Log!
[18:05:39] APP: Hello! Var=5
[18:05:39] HAZEL: Creating window Hazel Engine (1280, 720)
[18:05:40] HAZEL: OpenGL Info:
[18:05:40] HAZEL:   Vendor: Intel
[18:05:40] HAZEL:   Renderer: Intel(R) HD Graphics 4600
[18:05:40] HAZEL:   Version: 4.3.0 - Build 20.19.15.4331

this is from the console window

**Comment by IshoAntar** [comment]
I see, you're getting the error because your GPU doesn't support OpenGL 4.5, which is the version that introduced `glCreateVertexArrays`. see the [Documentations](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glCreateVertexArrays.xhtml)
to reproduce the issue i explicitly set the gl context's version using glfw's window-hints, in `WindowsWindow.cpp` before calling `glfwCreateWindow`, and i got that exception.
to fix it you can use `glGenVertexArrays(1, &m_RendererID)`, which should work.

**Comment by mjm2017** [comment]
And the exception comes to this line 
OpenGLBuffer.cpp line 15
glBindBuffer(GL_ARRAY_BUFFER, m_RendererID);

Say that my computer doesn't support the HW.. shouldn't HAZEL engine check that?

**Comment by Puddlestomper** [comment]
I think Cherno has mentioned that he has no interest in supporting pre 4.5 OpenGL, but yes Hazel should probably have an assert somewhere to check for this.

**Comment by IshoAntar** [comment]
> And the exception comes to this line
> OpenGLBuffer.cpp line 15
> glBindBuffer(GL_ARRAY_BUFFER, m_RendererID);
> 
> Say that my computer doesn't support the HW.. shouldn't HAZEL engine check that?

After i took a closer look, you'll have to refactor a lot of the OpenGL code to make it work with gl versions prior to 4.5, e.g in the `OpenGLVertexArray`, `OpenGLBuffer`, and `OpenGLTexture`, so it will require some work to be done.

> 
> 
> I think Cherno has mentioned that he has no interest in supporting pre 4.5 OpenGL, but yes Hazel should probably have an assert somewhere to check for this.

That could be done by an if statement that checks for the `GLVersion` values after initializing glad:
```C++
if (!(GLVersion.major) >= 4 && (GLVersion.minor) >= 5)
{
    // HZ_CORE_ASSERT or something
}
```
`GLVersion` is a struct defined in `glad.h` that holds the supported opengl version.

**Comment by LovelySanta** [comment]
I'll handle this as a bug, since this has been a common issue (too many times already).

I approve that someone create a PR to implement a more clear error for this, I'm thinking of:

1. hint glfw of the correct version (defaults to 3.3 core):
```cpp
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 5);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```
(see [the linux branch](https://github.com/LovelySanta/Hazel/blob/792ff772f3bb605c7c010f639bd63d9ed6fa05e0/Hazel/src/Platform/Windows/WindowsWindow.cpp#L51-L53) for details where to put this)

2. Assert the OpenGL version after we created a context, after logging the info:
https://github.com/TheCherno/Hazel/blob/734ea180bedd2334bdc3f1927635287be1e754ed/Hazel/src/Platform/OpenGL/OpenGLContext.cpp#L22-L25
```cpp
GLint versionMajor, versionMinor;
glGetIntegerv(GL_MAJOR_VERSION, &versionMajor);
glGetIntegerv(GL_MINOR_VERSION, &versionMinor);
HZ_CORE_ASSERT(versionMajor >= 4, "Hazel requires an minimum OpenGL version of 4.5!");
HZ_CORE_ASSERT(versionMinor >= 5, "Hazel requires an minimum OpenGL version of 4.5!");
```
Note: checking the profile for core/compatibility is more difficult: for example NVIDEA is setting the wrong flags, so checking this can result in a wrong assertment.

**Comment by mjm2017** [comment]
And shouldn't that variable be initialized?

**Comment by LovelySanta** [comment]
> And shouldn't that variable be initialized?

It only doesn't set it when no context is created (which it is), but it doesn't hurt to initialise it to 0...

**Comment by mjm2017** [comment]
This means also that I can no longer follow the project. I will not buy a new computer just to be able to compile this project.
This is bad.
