### ISSUE TITLE
Older devices might have issues with ImGui in OpenGL3

### ISSUE THREAD

**Issue by AlexanderSarton** [TheCherno/Hazel#192]
Hi,

I just started the Game Engine series a couple of weeks ago, and my workstation broke down just before I started the ImGui episodes. So I started working on my 2011 laptop with a GT 540M videocard.

It should have support for OpenGL 3.1, but I was having all kinds of exceptions when trying to run the code from episodes "ImGui" and "ImGui Docking and Viewports"

I know these are older episodes but I figured this might still occur for some people.

I figured out that I am able to run the application without any issues when switching to OpenGL 2 for ImGui. Also the docking works fine in that case. 

The only thing that needs to be done is include "imgui_impl_opengl2" instead of "imgui_impl_opengl3" and change the functions into the corresponding OpenGL2 equivalents.

I didn't make a pull request for this as I first like to know if this is something that should be supported for older devices. If this is interesting I would gladly look into an implementation for this.

**Comment by LovelySanta** [comment]
Since cherno mentioned multiple times that he only wanted to support OpenGL 4.5 and higher,  and having multiple unknown errors due to OpenGL version being too low, we added in an error message to inform people that we require OpenGL 4.5. Further on in the series we actually started using some of those features added in version 4.5.

https://github.com/TheCherno/Hazel/blob/0716731c8e274f2e3d83aefef2222fe189a33728/Hazel/src/Platform/OpenGL/OpenGLContext.cpp#L30-L35

On that note, after a quick search on nvidea, I found that the gt 540m does have support for opengl 4.5, so you should update your drivers for that and be fine.
