### ISSUE TITLE
Renderer2D can't render more than Renderer2DData::MaxTextureSlots different textures

### ISSUE THREAD

**Issue by Sarius587** [TheCherno/Hazel#214]
When trying to render more than ```Renderer2DData::MaxTextureSlots``` different textures using Hazel's Renderer2D the ```TextureSlots``` array overflows. This only occurs when you render these textures in one batch.

Probably the solution to this issue is to check if all texture slots are already used when submitting a new textured quad. If that is the case the renderer should flush and start a new batch via the ```Renderer2D::FlushAndReset()```method. The mentioned check has to be implemented in the two methods that actually submit a textured quad (normal and rotated). Maybe just replace
```
if (s_Data.QuadIndexCount >= Renderer2DData::MaxIndices)
    FlushAndReset();
```
with 
```
if (s_Data.QuadIndexCount >= Renderer2DData::MaxIndices || s_Data.TextureSlotIndex >= Renderer2DData::MaxTextureSlots)
    FlushAndReset();
```

This should make sure that the array doesn't overflow and also that all textures are rendered correctly.

**Comment by LovelySanta** [comment]
That would not be the best idea to implement it:
1.  Assume you have already 31 textures rendering (including the flat color one).
2. You request a new quad with new texture, so it will fail your if statement, not flushing, adding the 32nd texture and render that quad.
3. You request a new quad with an existing texture, it will pass your if statement and flush already, while it could still add this quad to the existing batch.

Instead, we should check the number of texture slots when it tries to add a new texture instead. So instead of adding it where you said, adding it to the place where the new texture is added to the batch:
```lua
		float textureIndex = 0.0f;
		for (uint32_t i = 1; i < s_Data.TextureSlotIndex; i++)
		{
			if (*s_Data.TextureSlots[i].get() == *texture.get())
			{
				textureIndex = (float)i;
				break;
			}
		}

		if (textureIndex == 0.0f)
		{
			if (s_Data.TextureSlotIndex >= Renderer2DData::MaxTextureSlots)
				FlushAndReset();

			textureIndex = (float)s_Data.TextureSlotIndex;
			s_Data.TextureSlots[s_Data.TextureSlotIndex] = texture;
			s_Data.TextureSlotIndex++;
		}
```

**Comment by Sarius587** [comment]
Oh, your right, apparently I didn't really think this through. Your solution seems pretty good.
