### ISSUE TITLE
Ignore imgui vcx.proj

### ISSUE THREAD

**Issue by L4ZZA** [TheCherno/Hazel#215]
Not a big deal, but can cause issues for inexperienced developers.

Steps:
1. clone hazel 
2. Initialize submodules
3.run script to generate solution

Bug:
ImGui submodule detects changes in the working directory.
![image](https://user-images.githubusercontent.com/17835185/79613671-df9add80-80f6-11ea-86ca-86160aee45ff.png)

Proposed solution:
- add file to `.gitignore` in imgui repository [this might need to fork the official repository, branch off the docking branch (i.e. hazel-master), commit changes in the submodule and then update hazel to point to the right imgui commit.

**Comment by LovelySanta** [comment]
Aren't all the `.vcxproj` files already been ignored? https://github.com/TheCherno/Hazel/blob/eb3f705b6097d81d8c743d19ecb239d4dfb94c0c/.gitignore#L12
Seems to not pop up in my git bash as an unstaged file...

**Comment by L4ZZA** [comment]
That only works for the hazel repo. 
Sumbodules are different repositories, so it needs that in each repository.

**Comment by LovelySanta** [comment]
Ah I see now, it is already in the GLFW gitignore, but this is not the case for ImGui, so that's why it is only showing up for ImGui. As you see above, I've made a PR to cherno's branch in order to add these to gitignore.

**Comment by freeman40** [comment]
An alternative solution would be to change the premake script so that it generates "out of source" build files.
Then, the .vcxproj's dont end up spread around in the source tree, and you dont need to worry about .gitignore, or accidentally committing something in the submodule.
Could also set it up so that different invocations of the build script generate projects for different systems (vs2019, cmake, whatever) all nicely separate from each other.
something like this:
root folder
  build      <-- premake script creates this.  add to .gitignore
      vs2019   <-- premake script create this. contains files for VS2019 build
          Hazel.sln
          Hazel.vcxproj
          Sandbox.vcxproj
          Imgui.vcxproj
          etc. etc.
   
      cmake    <-- or if you prefer, get premake to generate this
          <all the files required for cmake to build Hazel in here>

  Hazel           <-- this and everything below in git and version controlled, just as now
  Sandbox
  scripts
     win-GenProjects.bat

**Comment by L4ZZA** [comment]
I see what you mean, that's what I usually see in cmake-based project generation and I think that would be a quite elegant solution.

**Comment by LovelySanta** [comment]
It's already pushed to ImGui submodule, but we still can do this, in a seperate PR
