### ISSUE TITLE
Not an issue, just an FYI:  vcpkg integration causes link problems for Hazel

### ISSUE THREAD

**Issue by freeman40** [TheCherno/Hazel#220]
Just an FYI in case other people fall over this.
I use the [vcpkg](https://github.com/Microsoft/vcpkg) package manager for some other projects and had it integrated with Visual Studio.   I have imgui, glfw, and a bunch of other things installed via vcpkg.
A clean checkout and build of Hazel then fails to link (symptom: several hundred multiply defined symbols).
The problem is that Hazel links against it's own "imgui" library, and Visual Studio then helpfully adds in another imgui library (from package installed via vcpkg).
The solution is to _not_ have vcpkg integrated with VS

**Comment by IshoAntar** [comment]
If you want to use custom packages instead of the bundled submodules, you can omit the `--recursive` option when cloning the repo. i.e:
`git clone https://github.com/TheCherno/Hazel.git`
This will clone the main repository (`Hazel`) _only_ without the submodules.
also, if you do this you would need to fix the paths in the `premake5.lua` script to point to the correct directories.
