### ISSUE TITLE
Visual Studio Project Files

### ISSUE THREAD

**Issue by PhilipKatis** [TheCherno/Hazel#25]
Hello everyone!

I was wondering whether the already generated Visual Studio project files need to be in the repository, now that Premake is supported and anyone can generate them by themselves.

**Comment by MaximPrime** [comment]
Nope, they are useless in this case

niedz., 3 lut 2019, 12:04 użytkownik Philip Katis <notifications@github.com>
napisał:

**Comment by DrBarnabus** [comment]
It probably makes sense for them to be ignored, as it could be the case that someone is trying to build with an out of date configuration if they haven't been checked in after an update and someone clones the repository.

**Comment by Etosticity** [comment]
Nope, the Visual Studio Project files are obsolete when Premake comes in because everybody have different machine setups and Premake should generate them accordingly with your system's specs.

And like what @DrBarnabus said, things can get outdated pretty quickly, so its best if you compile and generate the necessary files the moment you finish cloning the repo 😃

**Comment by PhilipKatis** [comment]
Closing since this has been merged.
