### ISSUE TITLE
Why is the framebuffer applied in the EditorLayer?

### ISSUE THREAD

**Issue by paccc2** [TheCherno/Hazel#276]
Why is the framebuffer applied in the EditorLayer? Surely you want the final framebuffer to show the contents of all layers, then in the editor you can switch layers on and off as required.

Is the current solution meant as a temporary hack or the intended solution?

Thanks

P

**Comment by LovelySanta** [comment]
First of all, questions shouldn't be asked here. Join [TheCherno Discord Server](https://discord.gg/K2eSyQA) and as your questions there. It will keep github cleaner and you'll have answers a lot faster.

To answer your question. By enabling the docking space from ImGui, we don't have any visible Window to render to. So instead of rendering directly to the window as done in Sandbox, we render the final result into a framebuffer. This framebuffer we can display as a picture inside an ImGuiPanel that is dockable.

We could also render this framebuffer to the actual Window, like the one visible in sandbox, but that will be redundant, as that is what OpenGL already does in the backend.
