### ISSUE TITLE
imgui.ini under version control causes minor annoyance

### ISSUE THREAD

**Issue by freeman40** [TheCherno/Hazel#287]
#### Describe the bug
Not strictly a "bug", just a minor annoyance.
imgui.ini is under version control.
This file gets changed every time you run Hazelnut (imgui automatically saves window position and layout to this file).
This in turn means that git will say you've got changes in your workspace even when you haven't changed any code (the only thing changed is imgui.ini,  and usually in some non-important way (like the window is now five pixels further left).
Also, every time you do want to commit some code changes, you have to keep remembering to not commit imgui.ini

I do not think that imgui.ini should be under version control.

#### To Reproduce
(see description, above)

#### Expected behavior
imgui.ini not version controlled
Hazelnut should load imgui.ini if it exists (so that users window layout is still persistent), otherwise fallback to some sensible default window layout.

#### Screenshots
If applicable, add extra screenshots to help explain your problem.

#### Operating system: (please complete the following information)
- OS: win-64
- Version: Windows 10 2004 pro

**Comment by LovelySanta** [comment]
> imgui.ini not version controlled

No, we decided this in #204

> Hazelnut should load imgui.ini if it exists (so that users window layout is still persistent), otherwise fallback to some sensible default window layout.

Yes, but that's for later when we have a load cycle implemented. So this has no use as of now. See #204 as it explains our current workaround.

So I'm closing this for now. In the future we will load imgui files correctly.

**Comment by freeman40** [comment]
@LovelySanta   Thanks for pointing out #204.  I hadn't seen that (I only scanned the open tickets and PRs before embarking on this).
Anyway, having read through that, I still think my PR here is consistent with the discussion in #204.  You still have an ini file that specifies the initial layout for ImGui windows - you do _not_ end up with them in some unusable state, and you can still update the desired initial state if more panes or whatever are added.

All my PR really does is stops the annoyances that exist with having a "user preferences" file under version control - it should actually save the maintainers of the Hazel repo some work :-)

**Comment by LovelySanta** [comment]
> You still have an ini file that specifies the initial layout for ImGui windows - you do _not_ end up with them in some unusable state, and you can still update the desired initial state if more panes or whatever are added.

I disagree, if no ini file is found, it goes to some 'default', which can be unusable. From personal experience I can tell that running Hazel not on the primary monitor without docking resulted in the imgui rendering to be on the primary screen and since it was out of the window it was not even rendering it properly, or even crash on startup.

This is quite minimal and in this case I'm 100% behind cherno to not commit updates when unneeded, but not ignoring it until we have an implementation default in the future maybe. For similar reasons the profiler json files are also not committed but they aren't in the ignore list either.

**Comment by freeman40** [comment]
@LovelySanta  One of us is misunderstanding something.
The PR does not leave you with "no ini file found".   Instead, if there is no "imgui.ini" then the PR loads the imgui state from "EditorConfig.ini",  and that file has exactly the same content as the current imgui.ini file that is under-version-control-and-should-not-be-updated.

So, after the PR,  the startup behaviour for Hazelnut is exactly the same as it was before.  (except that now the initial imgui state is kept in a file that does not continually get updated every time Hazelnut is started up).

**Comment by freeman40** [comment]
Anyway, I don't want to cause trouble, and I totally appreciate all the work you put in as reviewer of PRs 👍  If the decision is only accept PRs that are strictly needed (I guess that means critical bugs only, right?) then no problem.   I guess I'm just a bit disappointed that the PR (which I put a little bit of effort into doing a reasonable job of) seemed like it got dismissed out of hand.  If there is actually a problem that the PR causes, then ofc I am happy to fix it (but only if PR would then be accepted :-) )

**Comment by LovelySanta** [comment]
> [...] if there is no "imgui.ini" then the PR loads the imgui state from "EditorConfig.ini", and that file has exactly the same content as the current imgui.ini file that is under-version-control-and-should-not-be-updated.
>
> So, after the PR, the startup behaviour for Hazelnut is exactly the same as it was before. (except that now the initial imgui state is kept in a file that does not continually get updated every time Hazelnut is started up).

I'm aware of what the PR does. However like I said before, this is more something that should be done in a load/startup routine of the engine, which we do not have in place so far (aka the famous `System` class that you might have heard of in other PRs). Until then, it's semi a good idea of implementing it, but rather holding of until we have it in place.

> Anyway, I don't want to cause trouble, and I totally appreciate all the work you put in as reviewer of PRs 👍 If the decision is only accept PRs that are strictly needed (I guess that means critical bugs only, right?) then no problem.

I 100% merge in bugfixes or code inconsistencies. For the other case I just evaluate for myself what cherno could tell about the suggestion/feature in a video. If it's too small for a video, I merge it in. Only when I know for sure that he doesn't want it, then I'll close it (like in this case). In all other cases I just label it accordingly and leave it open.

In this case, since there is no startup/shutdown routine yet (which is actually what cherno is working towards, a full pipeline of how the engine should work) it feels like too much of a feature to merge in just yet, nor to leave it open as I know cherno has his own solution for this problem.

> I guess I'm just a bit disappointed that the PR (which I put a little bit of effort into doing a reasonable job of) seemed like it got dismissed out of hand. If there is actually a problem that the PR causes, then ofc I am happy to fix it (but only if PR would then be accepted :-) )

I'm sorry if it seems like I quickly glazed over it and just closed it... It started with Gaztin removing the ini file at first in #42 (https://github.com/TheCherno/Hazel/commit/6481707b6821702dc5346d35886d8ea9ef6cb79e). After cherno brought it to his attention, he reverted the change in https://github.com/TheCherno/Hazel/commit/5c0d0b014111ff3e728646b11c170dd08057d90f. Around #202/#204 Cherno brought it to my attention to explicitly not merge that PR as he didn't want the ini file in gitignore, he rather worked on another solution (which the public branch of Hazel did not come around to yet). At the time Cherno did also answered that question in discord, which I then posted in https://github.com/TheCherno/Hazel/pull/204#issuecomment-583718303 as reason to why I was closing that PR. Since then I keep referring to #204 as why we don't ignore and/or have another solution for it.

So short story, it's not that I don't want to merge it, it's more that cherno asked me not to (for the few things he asks that).

I hope this answered most parts of your question?

**Comment by freeman40** [comment]
All good.  Thanks for the response.
