### ISSUE TITLE
Isn't this supposed to be a Registry group

### ISSUE THREAD

**Issue by DizzasTeR** [TheCherno/Hazel#291]
https://github.com/TheCherno/Hazel/blob/master/Hazel/src/Hazel/Scene/Scene.cpp#L69

In the latest episode, Cherno said "basically we should use a group" but he didn't change it from view to group.

**Comment by LovelySanta** [comment]
Also the rendering part could be optimized a bit by making it a [full-owning group](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#full-owning-groups) instead of a [partial-owning group](https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#partial-owning-groups).

> A partial-owning group works similarly to a full-owning group for the components it owns, but relies on indirection to get components owned by other groups. This isn't as fast as a full-owning group, but it's already much faster than views when there are only one or two free components to retrieve (the most common cases likely). In the worst case, it's not slower than views anyway.

So it could look a bit like the code below, however cherno had issues with the camera part when he tried this...
```cpp
// camera part
auto group = m_Registry.group<CameraComponent, TransformComponent>();
// rendering part
auto group = m_Registry.group<SpriteRendererComponent, TransformComponent>();
```

**Comment by DizzasTeR** [comment]
I did some testing, however I'm now even more confused, I tried this and it runs:
```cpp
auto group = m_Registry.group<CameraComponent>(entt::get<TransformComponent>);
```

However if you try anything else, such as changing the order of component (I don't actually know if that matters here, also when I checked the Wiki for entt) an assertion fails inside entt's code.

Configuration & Platform: Debug x64

**Comment by LovelySanta** [comment]
> I did some testing, however I'm now even more confused (...)

Cherno did look at #292 during his twitch stream, see https://github.com/TheCherno/Hazel/pull/292#issuecomment-670186645. As that commend says, after a deep dive we learned a lot about entt groups versus views.

Since he changed the name from group to view in https://github.com/TheCherno/Hazel/commit/8a81a7e75545eb62d8f87df69de827da710dc125, I'll close this issue as the confusion is solved (for now), however do note that it will probably change in the future.
