### ISSUE TITLE
Unnecessary overhead in native script function binding

### ISSUE THREAD

**Issue by Chlorie** [TheCherno/Hazel#303]
I see that Cherno is using hand-crafted type erasure for native script (to get rid of one pointer de-referencing of the vtable), but the use of `std::function` is totally unnecessary and can actually be avoided by using regular function pointers.

`std::function` has more overhead (space-wise and time-wise) compared with function pointers. Since the five lambdas don't have any large members (three of them are capture-less, and two of them only hold a reference which is the same size as a pointer) they can be stored in the small buffers. However, common implementation of `std::function` come with a small buffer capable of hold 2 `std::string` objects, compared to the lambdas in question that's much space wasted. And for debug build performance, calling through `std::function`'s layers of indirection is a pure pessimization, although it usually doesn't affect release builds, but why pay for something we don't use?

For this issue I suggest replacing the `std::function`'s with function pointers. The modification is straightforward as well, since non-capturing lambdas can be implicitly converted into function pointers, and although the "instantiate" function and the "destroy" function do have captures, it is easy to just add another parameter in for the pointer and pass in the pointer later.

I can send a pull request later if needed.

**Comment by LovelySanta** [comment]
We discussed this a bit on stream, and I suggested that as well at the time... Maybe create the PR and I can ask cherno to have a look at it during a livestream?

**Comment by Chlorie** [comment]
OK, PR opened.

**Comment by hyfloac** [comment]
I think the entire binding system is excessively slow compared to virtual tables. I did some testing, and even with optimizations in Clang (which in my experience has been the best at optimizing code), the amount of instructions actually required to complete the same task is huge. Don't forget that a VTable is just a list function pointers. This implementation is basically a VTable, that's more complicated, and uses a huge amount of memory. Normal VTables are stored once in static memory, but this object and its function pointers would have to exist per instance.

I have setup a simple demo of the generated assembly [here](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlICsupVs1qhkAUgBMAISnTSAZ0ztkBPHUqZa6AMKpWAVwC2tQVvQAZPLUwA5YwCNMxLpwBspAA6oFhdbT1DE0FvXzU6Kxt7IycXTndFZUxVfwYCZmICQONTTkSVcNo0jIJIu0dnVw8FdMzs4LyakrLo2KqASkVUA2JkDgByKQBma2RDLABqcSGdKgNaFLo2aexxAAYAQWHR8cwpmYA3ZKJiFfWtzbHmBQUJpmI8T3SHdmx6QgBPKc3xAHZZH4/X4AEWmAIuGyuNzuyAeTz0Rm8Nno5z%2B4M8BheeGQIHOE3xMLhWVQiLoWgIEHaE1oqEwAA8%2Bk99sCJlgqMwDKwCGDUZsCRMDnhMgY2BMAH73R7E0nIilUmn0xkEZmszDszncobgvEEwXC0UHVB4dATOg6YiYZgETCUnX4tFTEG8jb8vUEEWsAVGk10YGYGrEVAfW18gkOv6gwEu3VC90G72m2gAVU86CtNrQtBqEyorFQVtVXOY7TtjukjsjWydWudUNutiteCOkvhJKR5Jz1mWQPRDwO6dxofxLeer3eBA%2BACoJgB9axNBaYHlDiYgEA1dBruYLQrTHSG422obYWewy3WgCSWfSi%2BX0fxa43W/mi1oe4P6CPJ5nWADQavC59HepaPgQm4gNur7vt6EAjswLw4OOU4lses5mha6Z3vyoHgZBu6HDBcEIW8agTpOKHfr6/oEIGHxYQSOHPju/jQYeRFjqRU6kDmeZWhRaHJqmmE1psGJYjipYNmozawlKCLtvQlLUrSDKYE8pbYbO843n0EC0JyrBPMQJYruGTpRvyYpSU2mAjvJZKKfKKlKqWaIaQSeBUBAc7XiIfQmfe/JlrOv40f%2BvmLke5YRq55kQvy4gAKyyMlNL4AoLDEOgSWgolLKZtm7GIZx07aX5NpUgVyoKqpTIOha7rELQWkRUBWoVs6roJjOZ7piGgUOj1GGXq1FVgh1Fm6gm6HnmNpn/N8gX8p53kzemAVBWGC0zmt1reWVi4odFcUJXFpYfomfp/sGG1beCm34itO20FdYUfLdm2DVR137aNR0TQNZ0rhddApmme1VTx%2BbKlgRYfWW7mPV5z1g%2BtiPBSjQl7T5gGYNxsPpP9MXzZWpbWoiwjWnuE6eFozBGHsM4ACpnMDCYONYn7w25K78kNs0ATpezTCySWyJIbg5Upg0HX0Ko2AA7hAjEgDSBAIIGCtUszUUdSJS0Ej%2B1G0YL5UqmLUiS3l0v/Oj/Kw5g1oTE0ajID11yajozOTisv240TvMPTjQvywZRn0Z91baoH%2BLPeas3m8lUtFSRnzTpDsuYFSDou9i7s1Hu3u%2B5n7QALQrLtY3tTF%2BsPQJr20YnKXArBslPPBHFpxMGd/cFuduywBczEXx4QCX5fHt9b26zX91B6DWPC0MotJ9bKdIendDZpn3GQ7m0OFoTffpK7%2BeeyP2Bj39E/YAv4M2gTxbjbPsWk1HzoXQYi8QHvvEw8o6RuIqyOKoEge5rIySJPZWUZwJbdzbA5AgCgAo80CjQYgEAOREEtvAxEq5cEKSQdzW2McJgrTAGANAiIAB0mdKTw1OnPOu%2BIqGeGofzPqR07YElYdQyuUV0bE3ig9Xhd8%2BqPy4STVEQMNif0XgANVjB6H%2BW9lT7wLI/IB64wJrhAScPcdkEGyh9seHBrDEHIOkUwnMJBMEGGwXA1h%2BDzGyksfNax/JWE3zEXtCREcAZCPOHI%2B%2BDBrDAHYCo68UMNEAOYNxCBtk27SkIWYtsKCSGBVEYJe%2BEA/H60CZsYJ6ZQmiHYIo/UrBInZnUf/Is3FDEynJJvRE6TrFeIrtk8RsTJFVkrP0TorAQD9ESv0Ugph%2BhrFGagIZOg5ByGdt0XowtJBDE4KMggQzJntE6AAaxAIlNYQghncFGeMyZpBpn9FGQoEAhyNkTP6aQOAsAkCsLwOwMgFAVGIneZUK4ohOBrDWHkKg7zrTEBuRABwmzRkc1oBkD4Qy1mkCoQzegAB5WgrBEUPNIFgIwIhwkDHOfgC0KQjg3NxfSZI9iBjIusNaQZuLWB4AcMQBFegsBIvWQ8Iw3LOg0HoEwNgHAeD8EEMIUQKA5kyCEKym5kBOioCeP4Slpd0WSGuUkV8mhtD1FyKQcwLQKhxC8D4PwZp9A5BCOawoxqYiVEaNqwoxQ6hWoaPkY4qRailGsOUB1pqmhuqCAaoNvqogmq4J0BQiy%2BhRqOcM05MKLlDLpAADjcKXNw3Bu6SuABMQF1C1jUM4BMCAuBCAkCmCsvIEx5K/OINW1ZVJZkyDkOsmF2zSB7IOQmk5Yzk2XOubc0g9ytkDKGZq0gfLAWHLOVMoZHaHldqOBC/wIBuBAA%3D%3D%3D).

But in general it can be explained with these two functions:

```c++
void updateSingle(const float delta, NativeScriptComponent& comp)
{
    comp.onUpdate(delta);
}

void updateSingleVirtual(const float delta, ScriptComponent* comp)
{
    comp->onUpdate(delta);
}
```

Which generates the assembly:

```asm
updateSingle(float, NativeScriptComponent&): # @updateSingle(float, NativeScriptComponent&)
        sub     rsp, 24
        cmp     qword ptr [rdi + 152], 0
        je      .LBB2_2
        mov     rax, rdi
        mov     rcx, qword ptr [rdi]
        mov     qword ptr [rsp + 16], rcx
        movss   dword ptr [rsp + 12], xmm0
        add     rdi, 136
        lea     rsi, [rsp + 16]
        lea     rdx, [rsp + 12]
        call    qword ptr [rax + 160]
.LBB2_2:
        add     rsp, 24
        ret

updateSingleVirtual(float, ScriptComponent*): # @updateSingleVirtual(float, ScriptComponent*)
        mov     rax, qword ptr [rdi]
        mov     rax, qword ptr [rax + 32]
        jmp     rax                     # TAILCALL
```

I won't delve too deeply into exactly what each of these is doing, but basically in the first one it adjusts the stack, then checks to see if the function pointer is valid (which is what Cherno's code does, I don't know why since the lambda should generate no matter what), it then moves some things around and performs an indirect call.
The second function moves the VTable pointer (the VTable is always the first entry in a structure that has virtual functions) into the `a` register (`rax`, the 64 bit version), then it moves the pointer to the function (offset 32 bytes from the base of the VTable) into the `a` register, then it performs an indirect call (using an unconditional jump as a tail call, basically when the `onUpdate` function returns this function also has to return, so instead of 2 `ret` instructions, and multiple return jumps, there will only be one) to that function.

As a general rule of thumb, the more assembly instructions something takes, the slower it is. This obviously isn't always true, and is a lot more difficult to calculate due to out-of-order execution, but the slowest instructions are movement instructions (it's well known that modern computers are almost always data limited instead of compute limited, the processor is just so much faster than the memory), and the first function generates a lot more of movement instructions.

I haven't tested this with C-Style function pointers, but I don't think it would matter much, since they would still suffer from the same problem of having a per instance VTable instead of a global instance VTable.

**Comment by Chlorie** [comment]
@hyfloac Definitely, the type erasure method has its strength and weakness compared to general virtual functions. The type erasure method stores the object's function pointers directly in-place, while traditional virtual dispatching introduces an indirect look-up ("pointer chasing") to fetch the vtable first (maybe this would thrash the cache line) before it's able to make the indirect call. Could you test (godbolt or something) the version with function pointers please?

**Comment by hyfloac** [comment]
I've modified the test to use C-Style pointers. I also added a 3rd method which skips the test (it appears to be redundant and doesn't create a truly fair test). You can find the new test [here](https://gcc.godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAM1QDsCBlZAQwBtMQBGAFlICsupVs1qhkAUgBMAISnTSAZ0ztkBPHUqZa6AMKpWAVwC2tQVvQAZPLUwA5YwCNMxLpICspAA6oFhdbT1DE0FvXzU6Kxt7IycXTndFZUxVfwYCZmICQONTTkSVcNo0jIJIu0dnVw8FdMzs4LyakrLo2KqASkVUA2JkDgByKQBma2RDLABqcSGdADdkomJp7HEABgBBNfWx5gUFCaZiPE90h3ZsekIATymN8QB2WTu7%2B4ARaafNjZ29g%2BQjk56IzeGz0LYPT6eAxnPDIEBbCaIv4ArKoYF0LQECDtCa0VCYAAefROUyGrwmWCozAMrAIH3BGyRE1meEyBjYEwAfodjqj0aCsTi8YTiQRSeTKdTafTnusmSy2RzZqg8OgJnQdMRMMwCJhsQikRCpm8GXKkQqCOzWMyVWq6K9MDViKgrvrGYbHsb3rL5azLUrberaABVTzoHV6tC0GoTKisVA6inKdLtA2Io0Pb2bE1DT5bH77Ww6vDzHmAtEgzGx6xscGPLaeI6zCPw92Isunc6XAhXABUEwA%2BtYmrQ%2BjKzYjlaqIL2B/9tbqAJLR9KjzDtCBT9Cp3Npm3T2dYJ0u5cjvobrc7vNt/foGcDjVaiMbjvMM44bt9q97rf3%2B2OghnSuF9/l5N8uzUHte2/G9f1nOhQ3DXUQJRcCP0gvtSFjeMdRg9YoRhOE9yLNRS1A8t%2BUxbFcXxIlMBOPcmRAQdh1XPoIFoGlWBOYhUxvDMTR9JFORIktMA7IFK3oajhTohj%2BPrG8mTwKgICHFcRHPRiPWkQcj0Ak8NLXfVcy9PdM1NJlxDcWQbLxfAFBYYh0Gs943HJKMY1fd8Lgw/tWM0vUcU8sVZNFY1dK1S1iFoFijLHUyLKEydAznJ9dTdCcIsHecI1PNigo%2BMzktvINNQXQqFN07TERUtTHwqvisqsz0HwCdK9XUs91yKpKsr6n9A3/Y9XSalrPiZZTVLah0RrGyb01a4aDNdLqCqvYr%2BsEr4sq3INEIjCAQuwhMxSwWlmHmxaJoWiY6rag7kJq7KHrDQ61sCrDzpTXrtparNBtVfa3t1WxUAAFQAo66BjONTqTC6roi57XqQzqArXL7k0u8d/sspFdWBYRdWmHQe08LRmCMTBB3B5ZAbVBxrDvJGIRR3Kl3imnpnJazZEkAA2VzqKND613FXFMAAdwgEAQBqdA5bxAgEGdKWcQHcGTOqnMboWgd9KA/LAolvmpCF9yRcU5rbvOzBdQmJo1GQOddjpGZNd7ZY1IxrTEqU26xb6CXONYbjANx26LN3EqmTa8qI1Nmzhe8iDrn7Y7ffXbKndhV2alJz3vaz9oAFplgaw6NujvXJpmgCgKT2zXggVP0PTiZM65nEjVzl2WALj3wa9oZsAgEvy9H5agO1syY5txFUcTnmpmTy2298juu%2B6rDjrhxNvsunP0md/P3Z0IvR/H7vJ%2BwBCQb1Q/q918ztpr009oMB/oZXE6D%2BxrCcsFZy3mKoEgpNRJkRRJJDEYJR7m07hWWBBAFBNTZjeGgxAIDUiIAgtAwIJjMXwVJFBrNra3TuqpMAYBiEADos7YiRuNZ6TI6FpQqtrFhSI6GVwynhChA0A6Ih4SGb%2BT9I6LQBm/DYn8H4ADU/RWh/rDHCZ0AGEPlgQRWIBQGLFJhJJBAoR4rEFogyi9BUF1lrpg7BBhcGmOIYQsxJDLFVWesQ2%2B980YQHEfPPGLwAYyMDF/NGDBrDAHYMosU%2B81EXSwpA8S5E%2BQkLwRWNB5DuEVloV4w6vi8zSPWLI0J4T2Bg0hjUKJf9YnpHicWKBvIYEClScCdJtcRGPTsBDKGeS6yBMKcEh%2BYTRDsAUYqVglSYkIxqciBphjMQZzSVYvcHiK6iO8T0gJWx%2BidFYCAfobh%2BikFMP0VYhzUB7J0HIOQjtui9G5pIIYnBDkED2ac9onQADWIA3CrCEHs7ghzjmnNIOc/ohyFAgF%2BS8k52zSBwFgEgYheB2BkAoNDYEyLKg7FEJwVYqw8hUGRbqYgEKIAOFeYcpmtAMhXD2U80g%2BDqb0AAPK0FYLSmFpAsBGBEBEgYwL8BahSPMCFnLCTJDsQMel1hdS7M5awPADhiA0r0FgOlzyjhGHVZ0Gg9AmBsA4DwfgghhCiBQFcmQQhFUQsgJ0VAJx/CitLsyyQ4KkgpA0BAcw9RcikHMC0CocQvA%2BD8BqfQOQQghsKAGmIlRGjusKMUOo4aGj5AWKkWopRrDlFjUGpoyagi%2BvzVmqIgauCdAULcvo5a/n7MBRSkFeyCQAA4BalwFtwTuprgATFxbQ1YtDOATAgLgQgJApgPLyBMSSmLiATseTiS5Mg5DPIpe80gXyfm1oBUchtoLwWQtINCt5Oy9mutIFq3FvygVnL2aumF675gkv8CAbgQA%3D%3D), I've chosen to make it a separate version to reduce clutter.

The newly generated assembly looks like this:

```asm
updateSingleNoTest(float, NativeScriptComponent&): # @updateSingleNoTest(float, NativeScriptComponent&)
        mov     rax, qword ptr [rdi]
        mov     rcx, qword ptr [rdi + 40]
        mov     rdi, rax
        jmp     rcx                     # TAILCALL
updateSingleVirtual(float, ScriptComponent*): # @updateSingleVirtual(float, ScriptComponent*)
        mov     rax, qword ptr [rdi]
        mov     rax, qword ptr [rax + 32]
        jmp     rax                     # TAILCALL
```

I'm using the version which doesn't check the pointer first. You can still see the checked version in the GodBolt page, but it basically just has an additional jump, and the stack stuff from before is gone.

This code is much closer to a simple VTable, and potentially with some modifications may be identical. I haven't really looked at it deeply enough to determine if there is something I've done that is causing the additional move instruction.

As for the idea of pointer chasing, that sounds good until you remember that `NativeScriptObject` stores a pointer to the object instead of storing it in place, which it can't cleanly do due to the type erasure. It's the same thing as a virtual class, but just reversed. There is still the same level of indirection, just with a different object. It's also worth remembering that while the cache line is 64 bytes, you have several kilobytes to megabytes of cache, ie you have many cache lines. So while it will require two memory load operations, it's not going to be thrashing over the same cache line.

Another benefit of virtual functions is clarity. There is no ambiguity about what functions you can implement. You don't have to go chasing down the bind function and figure out the exact signatures necessary. You can simply look at the base class and figure out what can be overridden. If you have a tool like ReSharper it becomes even easier by being able to use generators to get a list of all potentially overridable functions, and then generating the exact signature correctly with little effort. I assume Visual Assist can do the same thing, but I don't use it.

**Comment by hyfloac** [comment]
Another thing to note about the cache lines. If you're iterating over an array of virtual objects that all have the same VTable, it may only require a single load for the VTable as it can be reused many times. On the other hand, with the `NativeScriptComponent` method everything is per instance, and even if the data is the same, the addresses are different, thus a memory load will be required for each individual objects "vtable".

**Comment by Chlorie** [comment]
OK this result is what I would expect from using type erasure, not that monster resulted from `std::function` 😄

> As for the idea of pointer chasing, that sounds good until you remember that `NativeScriptObject` stores a pointer to the object instead of storing it in place, which it can't cleanly do due to the type erasure. It's the same thing as a virtual class, but just reversed. There is still the same level of indirection, just with a different object.

No, it is not. You're storing `NativeScriptComponent` side by side in a vector, and in the virtual method case, `ScriptComponent*` side by side in a vector. So you're comparing a `NativeScriptComponent` (not a `NativeScriptComponent&`) with a `ScriptComponent*`. Calling a method on a `NativeScriptObject` is like 
*(get the pointer)->(follow the pointer)->(get the fptr)->(call)* 
while calling a virtual method on a pointer is like 
*(follow the pointer)->(get vtable pointer)->(follow the vtable pointer)->(get the fptr)->(call)* 
still one more indirection than the type erasure approach. Idk if I'm right to think this way...

Since the type erasure thing stores the fptrs inline less objects fit into one cache line as well 🤔
I cannot decide which approach is better, I think it's more of a "approach 1 is better in scenario A while approach B is better in scenario B" thing... Also the lack of IDE support is also a point to consider.

IMO type erasure is good when the API is clear to the user, `std::function` is a really good example of this. Also it is useful when you aren't the one in control of the class (trying to implement the API for 3rd party library class or even built-in types like `int`), being able to implement an interface without inheriting from any class is the main selling point in this case. For the kind of usage this issue concerns, maybe virtual method and overriding *is* better for clarity...

**Comment by hyfloac** [comment]
>>As for the idea of pointer chasing, that sounds good until you remember that NativeScriptObject stores a pointer to the object instead of storing it in place, which it can't cleanly do due to the type erasure. It's the same thing as a virtual class, but just reversed. There is still the same level of indirection, just with a different object.  

>No, it is not. You're storing NativeScriptComponent side by side in a vector, and in the virtual method case, ScriptComponent* side by side in a vector....

The point I was making about `NativeScriptObject` storing a pointer was not in relation to the function pointers. It was in relation to the object pointer. The actual object still needs to be passed to the function, and it is in a different part of memory and will require its own memory load.

The actual representation of the objects is more or less this:

```c++
struct ScriptComponent
{
    struct VTable
    {
        void(*onCreate)(ScriptComponent*);
        void(*onDestroy)(ScriptComponent*);
        void(*onUpdate)(ScriptComponent*, float);
    }
    VTable* _vTable;

    int x;
};

struct ActualScript
{
    int x;
}

struct NativeScriptComponent
{
    void(*onCreate)(ActualScript*);
    void(*onDestroy)(ActualScript*);
    void(*onUpdate)(ActualScript*, float);

    ActualScript* object;
}

void call(float delta, ScriptComponent* comp)
{
    comp->vTable->onUpdate(comp, delta);
}

void call(float delta, NativeScriptComponent* comp)
{
    comp->onUpdate(comp->object, delta);
}
```

My point was specifically related to the fact that `NativeScriptComponent::instance` is a pointer to some other portion of memory, instead of being in place, with actual memory directly beside the functions. Having the memory be in place is not possible with the current type erasure. As such, the data of the object would still need to be loaded, in the VTable version this is exactly the same, except that it's loaded when the program retrieves the data to the VTable. In terms of the amount of indirection, I don't think there is a difference. But the difference will show up in how often the VTable is loaded. With a true VTable the entire table is stored only once in the program, in the `.data` section (really it can be any section), whereas with Cherno's version it is stored multiple times throughout the program, even if the data is ultimately the same.

Looking back at the generated assembly, we can see that there are really only 2 loads for each function. The first function has 3 loads because of the registers where the data arrived, `rdi` is used to store the `this` pointer in `__thiscall` functions, but receives the first integer/pointer parameter in linux x86-64 (delta is a float and is thus passed in `XMM0`, probably). Had `comp` arrived in `rbx` or some other register, it should've only taken 2 move instructions, but it would still require 2 move instructions no matter what. The second function will also always require 2 move instructions as it has to doubly dereference the VTable.

**Comment by LovelySanta** [comment]
My experience is still not high enough to fully read the compiler explorer, but I'm getting better at it. It's not 100% of a true test, I'll try to explain why, but not sure if I'll make myself clear enough.

The way it works now, is that we create a component and bind (aka create) a ScriptableEntity to it, which holds the corresponding script functions OnUpdate etc. When it would work with virtual functions, is that we would attach the component to a ScriptableEntity, which derives from Entity itself. Since it has a ScriptComponent, we know it's a ScriptableEntity, and we can call those script functions on the entity (through the component which would still hold a pointer to the ScriptableEntity (= Instance). So in your case you have the script functions on the component, which is not what we want. The entity has the behaviour, while the components hold the data.

So now, the difference between those two is the way we call the script functions. In the current case, we use a lambda which will call the script functions (if defined, see future episode), so here it will
- check for nullptr (as it might not be a lambda) which will folow the pointer
- resolve the pointer to get the functionpointer
- call the function

Now when this was a virtual function, we would not need to check if the OnUpdate exist, as we know the base class has an (empty) implementation. However here it would need to look in the vtable to check if the derived class has an override, so
- get the vtable pointer
- get the fpointer from the vtable
- call the function

So that last example looks indeed promissing. I would not worry about memory times, as entt optimizes the components to be memory aligned depending on our groups/view usage. So I would expect that cache would be reasonably used...

As Chlorie said, the interface without inheritting from any class is the part that cherno likes about this, as this way we can link a stand-alone class (ScriptableEntity) to an Entity. I personally think the name ScriptableEntity is a bit 'weird' as I would've called it a Script instead, where each instance of script is attached to an Entity.

**Comment by hyfloac** [comment]
>The entity has the behaviour, while the components hold the data.

I haven't been paying close attention to the series, as I've been working on my own project, but that's usually not how an ECS works. The entity is merely a container of components, the components define the behavior, they also have their own state.

>As Chlorie said, the interface without inheriting from any class is the part that cherno likes about this...

If that is the case, then this method can still be used, but you would almost certainly want to take Chlorie's advice and use C-Style function pointers. But in the end I think you're just creating a typeless virtual call structure. There are a limited number of functions that the engine knows how to call, you can't just make a function and expect it to be magically called. The benefit of inheritance is that you know what functions can be overridden and will be called. You can still determine what those functions are with this system, but you have to dig into the bind function to determine their exact signature. Along with that, when designing a component, you know that it's going to be a component, thus you know that you'll need to extend the component base (assuming you go with a polymorphic route), you're not going to be taking some random object you happen to have and binding it to an entity, especially since it is unlikely that that object will conform to the requirements of the binding process.

**Comment by LovelySanta** [comment]
I agree that the C style function pointers are better, we discussed that on stream as well, and cherno did add a disclamer in the video saying that further testing was required...

And the way we're using the ECS at this point is that the scene is doing the work on the components atm, the script is linked to an entity, so it's fair that the script acts on the entity, which holds mainly an access point to a group of different component instances (of that entity).

I think a stresstest would be more appropriate. What about making X amount of SquareEntities and let them move a random amount through the script? I think that would be a fair test?

**Comment by ReDucTor** [comment]
`NativeScriptComponent` in its current form already falls apart because an entity can only have a single one so you cant have multiple of them bound to different things, and the whole secondary bind isnt great either.

Also you should never use number of instructions as any indicator of performance, you should always benchmark, and even then watch out your not just stuck in a microbenchmark that isnt realisitic.

Ignoring the obvious issue of you cant have multiple, it feels like the potential biggest performance issue here is really the intermediate state of it not being bound (side note destroy doesnt reset functions) so you have a bunch of null checks

**Comment by Chlorie** [comment]
I hasn't been paying close attention to this series either so I don't know how exactly the ECS works either.

> `NativeScriptComponent` in its current form already falls apart because an entity can only have a single one so you cant have multiple of them bound to different things, and the whole secondary bind isnt great either.

It really *is* a `ScriptableEntity` then since each `Entity` could only have one `NativeScriptComponent` attached... That's kind of weird since there're often times when you want to attach multiple behaviors to an entity...

> it feels like the potential biggest performance issue here is really the intermediate state of it not being bound (side note destroy doesnt reset functions) so you have a bunch of null checks

This maybe can be adjusted to be an advantage of this approach. You can allow the script class to implement each of the interface functions optionally, then you can use some template tricks to figure out whether the behavior class has the corresponding functions defined, if not defined set the corresponding fptr null. This *may* improve the performance when many entities don't implement some functions by replacing an indirect call to an empty function with a null check. (Considering many scripts may not need an `OnAttach` or `OnDestroy` this might help.)

**Comment by ReDucTor** [comment]
Finally ended up watching the video where all of this code was added and looked through the comments it looks like potentially Cherno wants to make `NativeScriptComponent` store multiple object, I'm not certain that I fully agree with that its kind of fighting against the ECS

Also the whole `ScriptableEntity` to provide helper functions around `this` is a bit of a smell for me its going to bloat out each component some more.

I would instead store the actual components in entt and start building a type registry which will generate functions that will iterate the registry for that type and call update passing in any desired arguments to access siblings (e.g. entity id, entt, entity, etc), then during the update for any types in that registry which require updating call the update which should iterate all of their instances, the same goes for any of the other functions (create/destroy/etc).

This removes all the different dispatching per-component to replace it with per-component-type dispatching, and also allows proper packing of components for better optimizations, gives a component the ability to opt-in for if it needs to use an entity or what ever during its update without having to pay the increased size cost, should be super cache friendly.

A naive implementation of this could be done ignoring the whole support different argument types for update and just make it always take the entity, additionally this sort of type registry then sets it up for future stages of having a list of components to add, a list of components to iterate for displaying in the editor and more.

This approach has many different potential optimizations which can be added on top of what I have described to get even more performance wins, but those probably aren't necessary and this approach should dramatically out do any of the other approaches described in this ticket.

**Comment by cc-marco** [comment]
As several pointed out , vtables boils down to the same thing as std::function, std function actually having extra logic to deal with std::function being not initialized and thus throwing an exception, here a godbolt for reference>
https://godbolt.org/z/E5xE8d

Function pointer would not change anything either, it would boild down to a mov, loading the pointer and than call it. Same as vtable. Also honestly I do believe this went ballistic and is overkill no matter the solution. 

What is the use case for this scripts? how many times do we expect to call this per frame? 10-20? Surely not 1000 times, because if this starts to be on a per entity basis then scripts is the wrong way to go, and we should leverage entt systems/jobs etc. 

So if is down to a handful of calls per frame, I doubt this is where the bottleneck of the engine is. To me personally, the virtual call is the lowest cost and less amount of boiler plate code imho.

**Comment by giordi91** [comment]
As several pointed out , vtables boils down to the same thing as std::function, std function actually having extra logic to deal with std::function being not initialized and thus throwing an exception, here a godbolt for reference>
https://godbolt.org/z/E5xE8d

Function pointer would not change anything either, it would boil down to a mov, loading the pointer and than call it. Same as vtable. Also honestly I do believe this went ballistic and is overkill no matter the solution.

What is the use case for this scripts? how many times do we expect to call this per frame? 10-20? Surely not 1000 times, because if this starts to be on a per entity basis then scripts is the wrong way to go, and we should leverage entt systems/jobs etc.

So if is down to a handful of calls per frame, I doubt this is where the bottleneck of the engine is. To me personally, the virtual call is the lowest cost and less amount of boiler plate code imho.

**Comment by hyfloac** [comment]
Alright, I created a benchmark, you can find the source [here](https://pastebin.com/cYKhVMcf).

For this code (which includes an increment, two calls to `rand`, a multiply every update) it took ~40 NS per instance for the virtual class, ~30 NS for a concrete class (no virtual calls, but not using the binding system), ~34-35 NS for binding with C-Style pointers, and ~35-37 NS for `::std::function`.

So I'll admit, I was wrong to assume that the binding system would be slower.

**Comment by giordi91** [comment]
@hyfloac  would you mind dropping your bench here? https://quick-bench.com/
It is made especially to do this kind of microbenches, and goes to great length to avoid to hit cache inbetween runs etc. To make it a not flawled benchmark.

**Comment by LovelySanta** [comment]
Closing this issue, see linked PR https://github.com/TheCherno/Hazel/pull/304#issuecomment-680723674
