### ISSUE TITLE
Textured sprite flicker when in perspective camera mode

### ISSUE THREAD

**Issue by standtall007** [TheCherno/Hazel#337]
The flickering happens when i am in perspective mode with the camera, and i move either the cameras Z position or a sprites Z position, and i use a textured sprite instead of solid colored sprite. If i use solid colored sprite(s) the bug doesn't happen.
Here's a link to an image of the bug:

To reproduce the bug you need to replace the current `Renderer2D::DrawQuad` with:
`
Renderer2D::DrawQuad(transform, m_Tex, 1.0f, sprite.Color);`
in Scene.cpp!

Where m_Tex is simply `Ref<Texture2D> m_Tex;` in the Scene.h.
And then in `Scene::Scene()` you need to create the m_Tex by doing something like:
`m_Tex = Texture2D::Create("assets/textures/ChernoLogo.png");` Just really use a texture of your liking, that is good enough.

Then all you need to do if you have done it correctly, is to build the project, use one of the cameras and switch its view mode from Orthographic to Perspective, and zoom out. you can also now try to move the sprites Z position further away from the screen and it should still flicker.

I expected it to not flicker at all.

![graphicBug](https://user-images.githubusercontent.com/11822856/94375346-42b38600-0113-11eb-86a9-1a6e3cb11cf8.png)

**Comment by babaliaris** [comment]
Can you show us the configuration of your perspective camera? Flickering usually happens because of [z-fighting](https://en.wikipedia.org/wiki/Z-fighting).

Also if you could post your GitHub repo, so we can download and test it by ourself (and see the code) would be easier to find out what's wrong.

**Comment by standtall007** [comment]
> Can you show us the configuration of your perspective camera? Flickering usually happens because of [z-fighting](https://en.wikipedia.org/wiki/Z-fighting).

It really doesn't matter which configuration i use on the perspective camera, because i already know what is causing the problem:
it is because we create and render a blank white texture at slot 0. and that interferes with the other texture.
And the only solution i could find to fix that problem, was to entirely pull everything about the white texture out of the code, but i don't know if that really solves anything.
 
> Also if you could post your GitHub repo, so we can clone and test it by ourselves (and see the code) would be easier to find out what's wrong.

Ok, here is it: https://github.com/standtall007/Hazel.
The only change i have made is this repo has high DPI adjustment added to it, but i have also tried to see if the problem occured without high DPI mode on, and it does.

**Comment by babaliaris** [comment]
I can't reproduce the problem. Well, first of all when I use the perspective camera everything is being clipped!
I can't figure it out though... Cherno has created some quite messed up renderer also the shaders are quite messy and I can't figure out what's going on. When you switch to the perspective camera, you can see the texture fine but just
flickering? Because I don't see it at all!

**Comment by standtall007** [comment]
When you say that everything is being clipped, do you then mean that you can't see any of the sprites?
Because if that's so, then you need to set the Z position to around +6.5 (positive, not negative) and if you set it higher you can of course see the sprite(s) getting smaller. Also the camera is normally set to 2.0 in the X axis, also this is the values for the Camera Entity, NOT the Clip-Space Entity. But try these values out and then write back the result. Also i think i had the camera entity's Z position to be = x: 0.0, y: 0.0, z: 8.5. I haven't changed the Fov, Near or Far at all. And the camera entity is set to primary.

**Comment by babaliaris** [comment]
It works fine for me: [video](https://youtu.be/xP-1-6n1xxM)

This is what I changed in the scene.cpp:
```c++
if (mainCamera)
		{
			Renderer2D::BeginScene(mainCamera->GetProjection(), *cameraTransform);

			auto group = m_Registry.group<TransformComponent>(entt::get<SpriteRendererComponent>);
			for (auto entity : group)
			{
				auto [transform, sprite] = group.get<TransformComponent, SpriteRendererComponent>(entity);

				//Renderer2D::DrawQuad(transform, sprite.Color);
                                 //THIS IS WHAT I CHANGED
				Renderer2D::DrawQuad(transform, m_Tex, 1.0f, sprite.Color);
			}

			Renderer2D::EndScene();
		}
```

**Comment by standtall007** [comment]
I have updated my answer but maybe it is that particular texture i'm using?

**Comment by standtall007** [comment]
I think i'm gonna close this issue for now, since it appears nobody else can reproduce the issue :( I have to take a guess that it is my GPU that is the problem though i honestly do not know for sure.

**Comment by babaliaris** [comment]
By the way, now that I remembered if the texture that you are using has dimensions that are not a power of 2 (for example 300x400) this can cause problems in some old drivers! Make sure the texture that you are using has dimensions like:
2x2, 4x4, 256x256, 512x512 , 1024x1024 . BOTH dimensions SHOULD be a power of 2. It is not required to be square you can also have images like 1024x512, as long as both dimensions are a power of 2!!!

This is because of something that is called alignment. Check it out [here (OpenGL common mistakes)](https://www.khronos.org/opengl/wiki/Common_Mistakes#Texture_upload_and_pixel_reads)

**Comment by standtall007** [comment]
That is not the issue, the texture is 16x16 so it is power of 2.

**Comment by babaliaris** [comment]
Then it's something else :) I just mentioned it cause I had a problem like that and took me a year to figure it out.

**Comment by standtall007** [comment]
btw when you have the two sprites overlapping but not directly at the exact same positions, do you the see the top sprite having some kind of alpha issue? My sprites show the background where they should be absolutely transparent.

**Comment by babaliaris** [comment]
No, I only see one texture (since the other one is behind it) and I don't see any background color.
It sounds like you have quite a lot of issues. It might be your GPU. If you are on windows and you play games
they probably work because DirectX does not have any bugs, but OpenGL might do! Nvidia might not really care
about OpenGL, Linus Torvalds  (the creator of the Linux kernel) once said that Nvidia is the work company that
they dealt with, and since OpenGL is mostly being used on Linux, then chances are that your card might have a bug.

**Comment by standtall007** [comment]
Yeah i thought so too. Well i do have a Amd vega i can put in and test with and report back.

**Comment by standtall007** [comment]
Alright so i have tested with the rx vega 64 and now the z positions work but the alpha blending still doesn't work properly:
![BlendIssue](https://user-images.githubusercontent.com/11822856/94725186-ac25d580-035b-11eb-93f0-64619969f0a1.png)

**Comment by standtall007** [comment]
> Alright so i have tested with the rx vega 64 and now the z positions work but the alpha blending still doesn't work properly:
Okay, i figured it out thanks to Cherno on his live stream today.

**Comment by hls333555** [comment]
Hi,
I have this weird issue both on RTX 2080MQ as well as RTX 2060 Super... Any ideas till now? Thx!

**Comment by LovelySanta** [comment]
It has to do with blend modes. Make sure you check OpenGL's blend modes to enable alpha blending correctly. That would be the most probable cause

**Comment by hls333555** [comment]
> It has to do with blend modes. Make sure you check OpenGL's blend modes to enable alpha blending correctly. That would be the most probable cause

This is my alpha blending mode:
`glEnable(GL_BLEND); glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);`
which does not seem to work...

**Comment by hls333555** [comment]
I have found that this issue can be fixed by making v_TexIndex flat.
See #362.
