### ISSUE TITLE
Left labels for ImGui

### ISSUE THREAD

**Issue by ilikenoodles2** [TheCherno/Hazel#342]
Cherno stated that the UI would look better with the labels on the left, and left it for homework.

A quick and easy solution is shown here: https://github.com/libigl/libigl/issues/1300, but this gets very repetitive.

A macro can be made for this:
 ```
#define IMGUI_LEFT_LABEL(func, label, ...) (ImGui::TextUnformatted(label), ImGui::SameLine(), func("##" label, __VA_ARGS__))
```
where the only changes would be from 
```
ImGui::Checkbox("Primary", &cameraComponent.Primary);
```
to 
```
IMGUI_LEFT_LABEL(ImGui::Checkbox, "Primary", &cameraComponent.Primary);
```

The macro can also be used like this:
```
if (IMGUI_LEFT_LABEL(ImGui::BeginCombo, "Projection", currentProjectionTypeString))
{
...
}
```

**Comment by LovelySanta** [comment]
Good idea. I still have some thoughts for you to think about:
1. It looks a bit weird to have a macro starting with `IMGUI_`, I would prefer to see a macro named something like `HZ_CORE_IMGUI_LEFT_LABEL`.
I opted to prefix it with `HZ_CORE_` rather than `HZ_` since Hazelnut should be seen as a part of the engine as Cherno stated before. It also indicates to someone from a game perspective that this is for Hazel engine use.
2. Somewhat contradicting my first statement, where should we define this macro? Should we define it in the `SceneHierarchyPanel` specifically? Or should we define it somewhere in the engine like in the `ImGuiLayer` such that it can be used everywhere?
3. If you saw Cherno show Hazel-dev, there you could change the width of the label compared to the width of the property itself, maybe this could also be implemented?
4. Another part of the homework was to create a DrawComponent function with a lambda (which could use this macro) to draw each property

**Comment by ilikenoodles2** [comment]
Taking a look at Hazel-dev's UI from a video, I was able to create something similar, if that's the direction headed.  Another macro would be used:
```
#define HZ_CORE_IMGUI_COMPONENT_VAR(func, label, code) ImGui::TextUnformatted(label); ImGui::NextColumn(); ImGui::SetNextItemWidth(-1); if(func) { code } ImGui::NextColumn();
```
It is more manual, as you would have to provide the name twice.  The macro wraps the if statement, which is needed, so additional ImGui code in the if block doesn't mess up the columns.  In total looking like this:
```
ImGui::BeginColumns(..., 2);
{
	HZ_CORE_IMGUI_COMPONENT_VAR(ImGui::DragFloat("##Far", &orthoFar), "Far",
		camera.SetOrthographicFarClip(orthoFar);
	);

        HZ_CORE_IMGUI_COMPONENT_VAR(ImGui::Checkbox("##Fixed Aspect Ratio", &cameraComponent.FixedAspectRatio), "Fixed Aspect Ratio");
}
ImGui::EndColumns();
```
![Capture](https://user-images.githubusercontent.com/36080054/95094055-15f10700-06ef-11eb-9767-ef0162680a90.PNG)

As for where to put the macros, one idea could be to make an ImGuiBuild.h file, which would include imgui.h, imgui_internal.h, along with the macros and functions to customize ImGui, for Hazelnut and the engine itself.

**Comment by dr01d3k4** [comment]
I wonder if it would be worth instead abstracting ImGui away by using functions like `static void floatSelector(string label, float value, std::function<void(float)> setValue);`, then `SceneHierarchyPanel::DrawComponents()` becomes easier to read and maintain.

I've tried to start something like that [on my own branch](https://github.com/dr01d3k4/Hazel/blob/template-component-panel-rendering/Hazelnut/src/Panels/ComponentRenderer.h), by moving the rendering for each component into a templated class so a game using Hazel can define its own renderer for its own components, and then I also added a `template <typename T> void renderEnumSelector(...)` as a start to making it reusable.

**Comment by LovelySanta** [comment]
> Taking a look at Hazel-dev's UI from a video, I was able to create something similar

Great job! That looks pretty nice!

> As for where to put the macros, one idea could be to make an ImGuiBuild.h file, which would include imgui.h, imgui_internal.h, along with the macros and functions to customize ImGui, for Hazelnut and the engine itself.

I think that would be a nice idea, I would wrap the functions inside a namespace, like within `Hazel::ImGuiBuild::` or something?
I'll try to remember to show this issue to cherno for when he records the next video! Great work so far 👍

**Comment by ilikenoodles2** [comment]
@dr01d3k4 renderEnumSelector sounds like a good idea, as well as having a renderer for each component.  However, a lot of it can be made compile time.  Instead of virtual methods in a class, maybe it could be a function template specialization.
```
template<typename Component> void DrawComponent(Entity entity);
template<> void DrawComponent<TagComponent>(Entity entity);
template<> void DrawComponent<TransformComponent>(Entity entity);
```
The name of each component renderer can be a ```static constexpr const char*```, because it's probably never going to change.  Also, a vector of renderers is unnecessary, because you will always attempt to draw all components.  Finally, although a minor detail, many people are scared of ```std::function``` nowadays.

**Comment by dr01d3k4** [comment]
Will game developers that use Hazel define custom components, or is it intended for them to only use script components? If it's the former, then we won't know in `SceneHierarchyPanel::DrawComponents()` what components we have to draw (unless there's a method in entt that gets all components? I couldn't find one). That's why I went with a vector that can be added to by the game developer, and a class that can be inherited from to easily add custom renderer logic.

That said, this could be replaced by a reflection system on components. i.e. if we know all the members of a component at runtime (possibly as getter and setter function pointers?), we can auto generate the UI for it. Possibly ties in to a serialization system too? But all this would be much further in the future I imagine.

**Comment by ilikenoodles2** [comment]
Yeah, you are right, I didn't consider runtime components(if there will be).  It would be a good idea then, to separate the components known at compile time, from the ones at runtime.

**Comment by LovelySanta** [comment]
Thanks everyone for contributing to the homework assignment. This is implemented in https://github.com/TheCherno/Hazel/commit/aab43e62129abc869d00ee508b4467bbe1c4f319, so I'll close this topic.
