### ISSUE TITLE
opengl version

### ISSUE THREAD

**Issue by Sangeet-Parashar** [TheCherno/Hazel#350]
Opengl 4.4 not supported. 
![Screenshot (17)](https://user-images.githubusercontent.com/67381460/96851104-479af980-1475-11eb-8edb-83259491abf7.png)

**Comment by Dreaner** [comment]
As far as I am concerned, this project will not support OpenGL under version 4.6 in the beginning.

**Comment by LovelySanta** [comment]
First of all, I see you're rendering using the integrated graphics of your CPU. Do you have any dedicated GPU? If so, you can set preferences (global or application wise) which GPU it should choose. I expect your graphics card to support higher than only 4.4.

We are using OpenGL 4.5 functions, so at least version 4.5 is required as of now. You could tweak the renderer a bit to support lower. Since this engine is still heavily a WIP, by the time it is finished, requiring OpenGL 4.5, or even OpenGL 4.6 should be of no issue.

Keep in mind that in the end, there will be other renderer support, for example Vulkan, or native renderers like DirectX (cherno mentioned 11 if i'm not mistaken).

I'll close this for now, as this is sort of intended at this point. Please go to our [Discord](https://discord.gg/K2eSyQA) if you require any help checking the graphics settings I mentioned before.

**Comment by Sangeet-Parashar** [comment]
Well I'm using intel HD graphics 5500 which supports opengl 4.4
