### ISSUE TITLE
Add HZ_PROFILE_FUNCTION()?

### ISSUE THREAD

**Issue by Dreaner** [TheCherno/Hazel#354]
In the recent commits, it seems that we did not use HZ_PROFILE_FUNCTION() for a long time. Do we need to add it in the functions we create in the new .cpp files?

**Comment by LovelySanta** [comment]
Yes and no, Yes we should provide the ability to profile the engine, however performance is only of interest during the runtime (starting from loading a game, playing the game and closing the game), this does not include the stuff inside hazelnut. But we might have to review parts of the scene and so on, as that might require profiling during runtime. Since we're actively developing it, I might suggest to hold off on that just yet, once we have the scene stuff wrapped up, it might be more of interest to see where this is required exactly

**Comment by Dreaner** [comment]
Thx, bro.
