### ISSUE TITLE
Backward Compatibility 

### ISSUE THREAD

**Issue by MMS-27** [TheCherno/Hazel#373]
<h1> OPENGL Backward Compatibility </h1> 

Hazel only supports OpenGL 4.5 and + but what about backward versions . At least it can support from Version 4.0 ? 
The latest is just 4.6 but hazel supports only from 4.5 everyone doesn't have new version of the pc .

**Comment by deadmann** [comment]
I'm using a Core2Due E6600 since 2005 :|

**Comment by MMS-27** [comment]
LOL I am using Intel i3 4030u with AMD Radeon Graphics But Its showing I cannot Use Hazel

**Comment by LovelySanta** [comment]
With some work, you can get it to work with 4.3, any lower is fairly unreasonable tbh... you can either ask in discord for help, or follow the youtube episodes, that should be 4.3. Some optimisations are done resulting in 4.5 as a minimum as of now.

**Comment by MMS-27** [comment]
But Other Engines Offer Even low Level Compatibility Why cant Hazel ?

**Comment by LovelySanta** [comment]
Cherno answered this question in an early video. By the time Hazel will be released, OpenGL 4.5 will be 'old'

**Comment by MMS-27** [comment]
But Still now Version 4.6 Is Just the Highest , How can Hazel not Support At Least 4.0 Or Something . Hazel is Even not a complete Engine But Even though it doesn't support OpenGL 4.0 ??

**Comment by DaveAxiom** [comment]
@MMS-27 I believe the justification is that by supporting an older version of OpenGL, the Hazel game engine would be a bigger development effort and everyone that is following this video tutorial series would be dis-serviced by learning obsoleted OpenGL library constructs.

I too would like it if Hazel supported older versions of OpenGL. I have an old laptop that is still working from 2007. It supports at best OpenGL 1.3 and it'd be great if I could use it to run/develop/toy with Hazel on it. I was disappointed when my favorite Open Source game raised its minimum version to 2.0 too! I've justified that it's fine for these projects to use a newer OpenGL version though since the hardware that supports v4.5 today is readily available. Version 4.5 is supported by video cards that I see on the used market for $30. Upgrading however small it is, is a cost but it's a small enough step to stay current.

**Comment by DaveAxiom** [comment]
I found this [old comment by Cherno](https://discord.com/channels/349857236656324608/643147843405611038/702418782613929996) in Discord:

_lots of things. Compute shaders, tessellation, spir-v, better debugging, better API for almost everything, SSOs, and quite a lot more. Whilst Hazel-dev runs on 4.5 as the minimum (with 4.6 soon to become required), it would be very difficult for it to support anything earlier than OpenGL 4.3, which was released in 2012, so for me OpenGL 4.3 is definitely a hard minimum, 4.6 highly preferred_
