### ISSUE TITLE
Linkage problem in vs2015

### ISSUE THREAD

**Issue by RohacekD** [TheCherno/Hazel#39]
If I generate solution by premake5 for visual studio 2015 I am getting this error:
`LINK : fatal error LNK1104: cannot open file '~\Hazel\bin\Debug-windows-x86_64\Hazel\Hazel.lib'`

**Comment by L4ZZA** [comment]
@RohacekD  It might not be obvious for everyone but issues should be expressed in the clearest and most specific way as possible so that whoever reads it doesn't have to guess what's happening where. 

Said so, with the little information provided, I can only assume that either your not exporting the _lib_ file from the code correctly i.e `__declspec(dllexport)` or that the location specified for the _additional libraries directories_ doesn't match the actual output folder.

P.S. Next time try to describe in more detail all the steps that lead you to that error message to make everyone's life (yours included) easier. :)

**Comment by Dragon9815** [comment]
@RohacekD You probably have an error in the Hazel project. For some reason Visual Studio still tries to build the Sandbox project, after the Hazel project build fails. This means that Hazel.lib doesn't actually exist, when Sandbox tries to build.

**Comment by Gaztin** [comment]
Closing since @RohacekD hasn't responded in a while. Please reopen if this is still an issue.

**Comment by TnVolsFan82** [comment]
Hello. I'm having the same issue as @RohacekD was having. How is this Hazel.lib created in the first place? Here is the error I receive after building the project: 5>LINK : fatal error LNK1104: cannot open file 'C:\Engine\Hazel\bin\Debug-windows-x86_64\Hazel\Hazel.lib'

**Comment by VagueLobster** [comment]
> How is this Hazel.lib created in the first place?
By building the solution, of course!
