### ISSUE TITLE
identifier "ImGuiTreeNodeFlags_SpanAvailWidth" is undefined

### ISSUE THREAD

**Issue by TNTMaster58** [TheCherno/Hazel#458]
In SceneHierarchyPanel.cpp, it says that ImGuiTreeNodeFlags_SpanAvailWidth is undefined. I have done download zip to make sure I haven't forgotten to write some lines but it still says that ImGuiTreeNodeFlags_SpanAvailWidth is undefined. How can fix that?

**Comment by LovelySanta** [comment]
`ImGuiTreeNodeFlags_SpanAvailWidth` is a `ImGuiTreeNodeFlags`, which is imported from `#include <imgui/imgui_internal.h>`. Since it errors on that line, could you check if you can find the `ImGuiTreeNodeFlags` itself? It might be a small typo at best.

Please refrain from asking help here for your personal code-along. For help with that, go to the `#game-engine-series` channel on [our discord server](https://discord.gg/thecherno). I'll close this as not an issue with the engine itself. If you encounter this with a fresh clone of github, feel free to reopen this topic.

**Comment by TNTMaster58** [comment]
Okay
