### ISSUE TITLE
Issue concerning scaling camera 

### ISSUE THREAD

**Issue by LongerZrLong** [TheCherno/Hazel#469]
https://github.com/TheCherno/Hazel/blob/74e7ed1d04c028dd5390763da3202db11521ed01/Hazel/src/Hazel/Renderer/Renderer2D.cpp#L140

I notice that when we scale a camera entity, it will affect the `TransformComponent` of the camera entity, and then affect the `ViewProjection` matrix through the line of code above. Therefore, as we begin the Scene with the following `BeginScene` function: 
``` c++
void Renderer2D::BeginScene(const Camera& camera, const glm::mat4& transform)
{
HZ_PROFILE_FUNCTION();

s_Data.CameraBuffer.ViewProjection = camera.GetProjection() * glm::inverse(transform);
s_Data.CameraUniformBuffer->SetData(&s_Data.CameraBuffer, sizeof(Renderer2DData::CameraData));

StartBatch();
}
```
 and drag `Scale` of `TransformComponent`, it will cause the following result: 

**Before Dragging Scale X**
<img src=https://user-images.githubusercontent.com/85812701/127947809-149d647f-6d3c-4a12-9730-1885302c4a26.png width=30% height=30%>

**After Dragging Scale X**
<img src=https://user-images.githubusercontent.com/85812701/127948079-e33a0472-e1c2-4ee0-9079-cd98a6746754.png
width=30% height=30%>

I wonder if this is a desired feature or is a minor bug? Cuz scaling a camera will take no effect in 3D Modeling Software like Blender or Game Engine like Unity.

**Comment by IshoAntar** [comment]
I think it's supposed to be like that.
It also looks like that in blender,

Before:
![before](https://user-images.githubusercontent.com/32076082/127976249-9cbf03d1-0b46-4f05-9d92-70f67fcb028f.png)

After:
![after](https://user-images.githubusercontent.com/32076082/127976303-7033069f-e192-4dfa-9859-a37d4fdc3362.png)

Correct me if i'm wrong, but i think that if you want to compare Hazel's rendering to Blender, then what hazel renders is only blender's camera view, *not* the whole (blender) scene.

Since when you're scaling the camera's X component, *should* (?) affect the whole viewport. Since the viewport is viewed through the camera.

**Comment by LongerZrLong** [comment]
Thanks for your quick reply, I will take a closer look at the code.
