### ISSUE TITLE
I have added the transform component UI to my Engine and it's working good but there is a slight problem which is the scale on the z axis doesn't work. why is that ? and how to fix it ?

### ISSUE THREAD

**Issue by FlyingStudent** [TheCherno/Hazel#671]
#### Describe the bug
A screenshot or copy of the error could be helpful as well.

Make sure your bug can be reproduced with the Hazel Engine and not by your own engine that you're creating alongside with Hazel. For issues with your own engine, we're happy to help you in [TheCherno Discord server](https://thecherno.com/discord). Thanks for your understanding.

#### To Reproduce
4. See error above

#### Screenshots
If applicable, add extra screenshots to help explain your problem.

#### Operating system: (please complete the following information)
- OS: [e.g. win-64]
- Version: [e.g. Windows 10 home]

**Comment by VagueLobster** [comment]
Dude don't make a whole new issue just to type on the rest of your issue! You could just as well have edited to first one to be way more descriptive instead! But the Scale on the Z isn't a bug in Hazel 2D, it's not meant to do anything since it's a 2D game engine!
It would require 3D meshes for it to do anything!
