### ISSUE TITLE
11

### ISSUE THREAD

**Issue by kabosusang** [TheCherno/Hazel#672]

**Comment by VagueLobster** [comment]
You know, this isnt't the right place to advertise your engine... this is afaik meant for Hazel 2D issues...
I know, i could be wrong 😄
But if you join Cherno's discord instead and go to the advertise-and-showcase channel, and show your engine in there, then that would probably be a better fit, since people come in here to find issues that may be resolved and/or find issues they can help solve 😃

**Comment by kabosusang** [comment]
😭I'm sorry for providing the wrong issule. Can you delete this issue for me?

**Comment by VagueLobster** [comment]
> 😭I'm sorry for providing the wrong issule. Can you delete this issue for me?

I don't have those kinds of privileges, so i can't. But don't cry, you just didn't know, and that's fine 😄 But now you know for future references 👍
