### ISSUE TITLE
Problem when running Project on Intel GPUs

### ISSUE THREAD

**Issue by FlyingStudent** [TheCherno/Hazel#679]
Hi Everyone 
I am really sorry for this but i thought that I Used an Intel GPU while i use an amd GPU:
![Screenshot (245)](https://github.com/TheCherno/Hazel/assets/138330536/73d306d2-8a7c-4c52-bc88-a60fb3398079)
Now, What is the solutoin for my problem?
My problem was that I am getting an opengl invalid enum and i think that the problem is due to GL_SHADER_BINARY_FORMAT_SPIR_V.
Here goes the image for the error that's occuring :
![Screenshot (244)](https://github.com/TheCherno/Hazel/assets/138330536/1fa8ed26-7e8d-46e0-a48b-66fa53059281)
Now, if I am using an AMD GPU why that problem occurs @VagueLobster ?

**Comment by Kirdow** [comment]
Top line in the console output says 
> Renderer: Intel(R) HD Graphics 520

I'm gonna assume you're on a laptop, since laptops usually have a thing where they default to your CPU's integrated graphics and then use the GPU when you explicitly tell it to. My suggestion is to look up how to do this for AMD unless VagueLobster knows.

Another possibility if you use a desktop PC is that you connected your monitor to the motherboard instead of your graphics card. This causes your main GPU to be that of the motherboard, which is the CPU integrated graphics. (This is also why laptops default to the integrated GPU from the CPU, since the laptop monitors usually connect to the motherboard.) If this is the case, reconnect the monitor cable from the motherboard slot at the back of your PC and instead connect it to the GPU card itself. Then the problem should disappear.

**Comment by VagueLobster** [comment]
> Top line in the console output says
> 
> > Renderer: Intel(R) HD Graphics 520
> 
> I'm gonna assume you're on a laptop, since laptops usually have a thing where they default to your CPU's integrated graphics and then use the GPU when you explicitly tell it to. My suggestion is to look up how to do this for AMD unless VagueLobster knows.
> 
> Another possibility if you use a desktop PC is that you connected your monitor to the motherboard instead of your graphics card. This causes your main GPU to be that of the motherboard, which is the CPU integrated graphics. (This is also why laptops default to the integrated GPU from the CPU, since the laptop monitors usually connect to the motherboard.) If this is the case, reconnect the monitor cable from the motherboard slot at the back of your PC and instead connect it to the GPU card itself. Then the problem should disappear.

@FlyingStudent I agree with Kirdow: Look it up on google on how to this for AMD, as i am using an Nvidia GPU myself!

**Comment by FlyingStudent** [comment]
Thanks you all I am really thankful for having such gorgeous community to help me ❤❤
I am going to try it out and tell you with the result before closing the comment.
Thanks again for your help @VagueLobster, @Kirdow

**Comment by FlyingStudent** [comment]
Morning Everyone!
My problem ain't solved yet.
I learned how to change the current active GPU to AMD so i changed visual studio to use but as it turned out, I need to change the project I am running itself to use it because even though visual studio is using the AMD GPU my project runs on intel as the debugging window shows when i run my project.
Can anyone help me with that ? 
Thank you all for support I really appreciate it .
Have a nice day

**Comment by FlyingStudent** [comment]
Update:
problem is nearly solved.
when i plug my power adapter it switch to the AMD GPU but when there's no power it doesn't automatically.
Working on it

**Comment by FlyingStudent** [comment]
Problem is solved ! 
Now, I am using my AMD GPU instead of my intel GPU.
Thank you all for your support. It was really helpful
Thanks Yan for this beautiful community that you have created ❤❤
Thanks @Kirdow , @VagueLobster  for your support . you were a huge help ❤

**Comment by viktorpopp** [comment]
Please close the issue.
