### ISSUE TITLE
Removing ImGui

### ISSUE THREAD

**Issue by lameman2000** [TheCherno/Hazel#69]
Hi,
I was trying to remove ImGui in replace of my own GUI library, however, when the file ImGuiBuild.cpp is removed it throws this error:
![vsscanferror](https://user-images.githubusercontent.com/52321359/60343875-45a94f00-9983-11e9-9206-813d4ec4962b.png)
Or, in text:
LNK2019
unresolved external symbol __imp___stdio_common_vsscanf referenced in function _vsscanf_s_l
Project: Sandbox
File: glad.lib(glad.c.obj)
Line: 1

And, the error is irreversible, in the sense that once it occurs, if you add the file back again, the error stays. There is no way (that I can tell) to get rid of the error once you get it, other than reverting to a backup. An interesting thing to note is that the error is occurring in the Sandbox project, and that Hazel itself builds completely fine.

**Comment by Gaztin** [comment]
`__stdio_common_vsscanf` is a CRT (C runtime) function, so this means that you somehow aren't linking to the runtime correctly, or that glad is linking to an old version of the runtime.

The error is only occuring in your Sandbox project because it's a linker error, and the compiler isn't doing any linking when building static libraries.

**Comment by CleverSource** [comment]
This is unrelated to the Hazel repository and is a personal issue. This should be closed and if @lameman2000 wants to further discuss his issue he should discuss it via [TheCherno Discord server](https://discord.gg/K2eSyQA).
