### ISSUE TITLE
Updating submodules

### ISSUE THREAD

**Issue by 161134050** [TheCherno/Hazel#89]
It seems that submodules in Hazel/vendor are frozen on commits from many months ago, what is the process for updating these submodules to the latest commits of their respective repositories?

Cheers

**Comment by DaveAxiom** [comment]
#82 Changes the Hazel repository to the newest commits on submodules that were updated for Linux support. Notice too that the submodule repositories are forks by TheCherno.

**Comment by LovelySanta** [comment]
To add to what DaveAxiom said and to answer your question:

To update a submodule, the repository points to a specific commit of the submodule. One have to manualy checkout the submodule and pull the new commits off that submodule (moving the repository pointer to a newer commit of the submodule). As final step, you commit your changes as any other commit and push to github.

Specific in our cases; imgui has been updated to the docking branch at some point and in #82 we edited the premake files in those submodules. However in the GLFW there is still an issue that is addressed in #84.

Since this covers this whole issue; I'll mark this issue to be closed when #82 gets merged.

**Comment by CleverSource** [comment]
I do agree that submodules should be actively updated. ImGui's docking branch has been updated quite a bit and has had major optimizations so it would totally be a thing to look into.

**Comment by LovelySanta** [comment]
When major updates happen to the submodules, we can update them indeed.

> ImGui's docking branch has been updated quite a bit and has had major optimizations so it would totally be a thing to look into.

You can make a PR on [TheCherno/imgui](https://github.com/TheCherno/imgui) to pull updates and add that PR onto this PR's todo list. (Like we did for example in #82 )

**Comment by CleverSource** [comment]
@LovelySanta Actually updating imgui's docking branch would require changing some Hazel code; reason being is because some flags were completely removed or enabled by default so some Hazel code can break.

**Comment by LovelySanta** [comment]
> @LovelySanta Actually updating imgui's docking branch would require changing some Hazel code; reason being is because some flags were completely removed or enabled by default so some Hazel code can break.

Thats why I tried explaining the steps to be taken:

1. Create a branch on your fork, fork cherno's ImGui branch
2. Update your ImGui branch to a more recent (somewhat acceptable stable) commit
3. Change the submodule on your fork to include your (updated) ImGui submodule
4. Change Hazel code to work with the (updated) ImGui submodule
5. Create 2 PR's:
    1. To cherno's ImGui fork to update ImGui to the updated commit
    2. To Hazel, with a todo list to merge the above PR
6. Once cherno's fork of ImGui is updated, update your Hazel fork to use cherno's fork of ImGui again & mark off the todo list
7. Now the Hazel PR has a full updated ImGui and the PR can be merged into Hazel.

Hope this makes a bit of sense?

**Comment by LovelySanta** [comment]
Since updating ImGui will resolve some memory leaks, I'll mark this as a bug, so it should get some priority to get implemented.
