### ISSUE TITLE
Update Premake to compile alpha 14 frome source

### ISSUE THREAD

**Issue by ghost** [TheCherno/Hazel#90]
The current Premake in this repo is the version 5.0.0-alpha13 that doesnt support VS2019 solutions, please update this to alpha 14. Btw in my fork of Hazel i updated this and everything works fine on VS2019 solutions.

![](https://cdn.discordapp.com/attachments/496257118098292736/606936423358005281/unknown.png)

![](https://cdn.discordapp.com/attachments/496257118098292736/606936909452673072/unknown.png)

**Comment by LovelySanta** [comment]
Can confirm, alpha13 does only support up to vs2017: 
![image](https://user-images.githubusercontent.com/26593477/62395950-0c5f9280-b572-11e9-8fcf-a65a4cdb4f05.png)

As jgsabatini pointed out to me; vs2019 is supported in alpha14
![image](https://user-images.githubusercontent.com/26593477/62395983-24cfad00-b572-11e9-8dc4-3ed48fa48cb6.png)

**Comment by WhoseTheNerd** [comment]
Premake 5 binaries shouldn't be on github repository, My idea is to use a script that downloads and builds the latest premake5 binary.

**Comment by CleverSource** [comment]
Just wanted to touch on this, will the binaries be updated or should someone consider making a PR based on @WhoseTheNerd's idea (or WhoseTheNerd himself could make the PR).

**Comment by LovelySanta** [comment]
I wanted to note: Someone started building premake from source, but that was only for vs2019. I started a week ago with building premake from source ([LovelySanta/Hazel branch project-gen-win](https://github.com/LovelySanta/Hazel/tree/project-gen-win)). However keeping compatibility with vs2017 gave some issues (premake/premake-core#1319) and is waiting for a fix.

So we can update the binaries to alpha14 to get the vs2019 generation (which works perfectly well by generating vs2017 files due to vs backwards compatibility), or we can just update to adding it as a submodule and building localy...

**Comment by LovelySanta** [comment]
Premake has been updated to alpha 14 in https://github.com/TheCherno/Hazel/commit/b62acd9c0c37c3b632bcf93f8ab404537cd0528b. I'll leave this issue open to convert the binaries to including premake5 as a submodule and compile from source instead.

**Comment by LovelySanta** [comment]
I'll close this, for a more detailed reason why, read my comment (https://github.com/TheCherno/Hazel/pull/154#issuecomment-544192051) on the PR.
