### ISSUE TITLE
Singleton Input class

### ISSUE THREAD

**Issue by moskittle** [TheCherno/Hazel#97]
``Input`` class is a singleton. Therefore, its copy constructor and copy operator is supposed to be ``delete`` functions to prevent from copying this class. 
However, in ``WindowsInput.cpp``, the line,

``Input* Input::s_Instance = new WindowsInput();`` 

is trying to use copy operator(which I have ``void operator=(const Input&) = delete;``) in ``Input`` class. 

If an ``Input`` constructor is explicitly declared and defined, it seems like this problem will be solved, but I not sure how this is working.

**Comment by moskittle** [comment]
There is one thing I don't quite understand.

I explicit add ``	Input(const Input&) = delete;`` and ``void operator=(const Input&) = delete;``.
When I call ``Input* Input::s_Instance = new WindowsInput();``, it will throw an error ``attermpting to reference a deleted function``. 

However, if I explicitly declare ``Input() = default;``, the compilation would suceed. 

Does anyone know how this works?

**Comment by LovelySanta** [comment]
In Input.h we only define the variable without having any instance:
https://github.com/TheCherno/Hazel/blob/f52b813db65cd7275da56003c501914ad1c7515a/Hazel/src/Hazel/Input.h#L24
Meaning, when creating the first instance (using `new WindowsInput()`) it will resolve all the static fields, resulting in s_Instance to have a default constructed instance.

We got 2 options:

1. As we're doing now, overwriting the s_Instance
2. Initialize the s_Instance
`static Input* s_Instance = nullptr;`

Can you try that? set Input::s_Instance to nullptr, then deleting, it should work?
If it was up to me, I would also declare a protected Input default constructor as
```cpp
protected:
    Input() = default;
```

**Comment by Puddlestomper** [comment]
I implemented @LovelySanta's suggestion and found that creating the protected default constructor for Input and deleting the copy constructor and copy operator compiled with no errors without having to initialize s_Instance to nullptr. Not sure why this works, but it compiles and runs without error so it seems fine.

I thought I'd also note that it seems that initializing s_Instance must be done in a translation unit (not in Input.h) which would require creating Input.cpp or doing it somewhere else like in Application.cpp.

**Comment by LovelySanta** [comment]
> I implemented @LovelySanta's suggestion and found that creating the protected default constructor for Input and deleting the copy constructor and copy operator compiled with no errors without having to initialize s_Instance to nullptr. Not sure why this works, but it compiles and runs without error so it seems fine.

Making the default constructor private/protected has nothing to do with it. That only prevents the user from making an Input class (only derived classes allowed).

The line that actualy fixes your errors is `static Input* s_Instance = nullptr;`.
1. Assume it is not there.
We create a new WindowsInput, derived from the Input class. It will create an Input (base class) instance. While it is creating this (first) instance of the Input class, it will resolve all static fields that are not initialized. This means creating an Input class using default constructor to initialize that s_Instance. After the constructor, it wants to assign a WindowsInput to an existing Input instance, where it wants to use the copy constructor or assignment operator.
2. Now assume it is there.
It won't be initialised, as it is a nullptr, not actualy pointing to an object, it will point to null. Once it tries to assign the WindowsInput, it won't try to use the copy constructor or assignment operator, and just let the s_Instance point to our newly created WindowsInput.

This is something we might want to fix, we never know what we'll be adding in the future to the Input class. Hence why I'll mark it as an optimalisation.

**Comment by Puddlestomper** [comment]
> The line that actualy fixes your errors is static `Input* s_Instance = nullptr;`.

I think you misunderstood me. This was not fixing my errors simply because it was not in my code.

I have done some more testing and I think the error when deleting the copy constructor and copy operator is not to do with the copy operator, but rather the creation of the WindowsInput instance. As far as I can tell the following happens:

1. We delete the copy constructor and copy-assignment operator.
2. As per [the Microsoft Docs page](https://docs.microsoft.com/en-us/cpp/cpp/explicitly-defaulted-and-deleted-functions?view=vs-2019) (the first bullet point) and because we declare the copy constructor (even if only to delete it), the default constructor is not generated anymore.
3. We get a compiler error on construction of WindowsInput because no default constructor exists.

This is why explicitly declaring the default constructor solves the issue. You are right in saying the protected label has nothing to do with it.

As far as I can tell the compiler sees the `Input* Input::s_Instance = new WindowsInput();` line as the initialization of s_Instance and so it doesn't call the copy-assignment operator. I don't think static members are initialized by default constructors, since then they could be initialized multiple times if multiple instances are created. Also the wording on [cppreference's default constructor page](https://en.cppreference.com/w/cpp/language/default_constructor) under the "Implicitly-defined default constructor" section seems to imply only non-static members are initialized.

Thus, it seems that all that's needed is to delete the copy constructor, delete the copy-assignment operator, and declare the (preferably protected) default constructor:
```c++
protected:
	Input() = default;
public:
	Input(const Input&) = delete;
	Input& operator=(const Input&) = delete;
```

**Comment by LovelySanta** [comment]
First of all, let me say that I agree with your implemenation and what does/doesn't need to be present. I only think you misunderstood me a bit with this:

> I don't think static members are initialized by default constructors, since then they could be initialized multiple times if multiple instances are created. Also the wording on [cppreference's default constructor page](https://en.cppreference.com/w/cpp/language/default_constructor) under the "Implicitly-defined default constructor" section seems to imply only non-static members are initialized.

Static members are initialised 100% sure before you use anything that has to do with the class/getting/setting the variable. The only thing that is not clear is when they are initialised as there are 2 main answers to this (see this nice [stackoverflow post](https://stackoverflow.com/questions/1421671/when-are-static-c-class-members-initialized) where I assumed it was before you created the WindowsInput instance (2nd option of the stackoverflow post).

**Comment by moskittle** [comment]
@LovelySanta @Puddlestomper Thanks for the discussion on this issue and awesome external references.
